version: "3.9"
services:
  web:
    container_name: "rd_app_web"
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "8920:8910"
    environment:
      SESSION_SECRET: XTL532AMCZf862yJfWbTRgnPwjQ7w5TUTcZvK9B6i3GkV5tpESspu5J9Ai4UNaUG
  api:
    container_name: "rd_app_api"
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8921:8911"
    environment:
      DATABASE_URL: file:./dev.db
      SESSION_SECRET: XTL532AMCZf862yJfWbTRgnPwjQ7w5TUTcZvK9B6i3GkV5tpESspu5J9Ai4UNaUG
