FROM node:16

ENV LANG=C.UTF-8

RUN apt update

WORKDIR /app

COPY .nvmrc .
COPY graphql.config.js .
COPY package.json .
COPY redwood.toml .
COPY yarn.lock .

RUN yarn install
RUN yarn add react react-dom @redwoodjs/api-server @redwoodjs/internal --ignore-workspace-root-check

CMD yarn rw dev api
